#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar"
ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins" # Needed inside of the sourced scripts

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

sketchybar --default icon.font="Hack Nerd Font:Bold:17.0"  \
                     icon.color="$WHITE"                   \
                     icon.padding_left=10                  \
                     icon.padding_right=4                  \
                     label.font="SN Pro:Bold:14.0"         \
                     label.color="$WHITE"                  \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     background.color="$ITEM_BG_COLOR"     \
                     background.corner_radius=5            \
                     background.height=24                  \
                     padding_left=5                        \
                     padding_right=5 

# Left-side items
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right-side items
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/brightness.sh"

#### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
