[
  {trigger: "mk", replacement: "$$0$$1", options: "tA"},
  {trigger: "ali", replacement: "$$\n\\begin{align}\n\t$0\n\\end{align}\n$$", options: "tw"},
  {trigger: ";;", replacement: "\\text{$0}$1", options: "mA"},
  {trigger: "cal", replacement: "\\mathcal{$0}$1", options: "mA"},

  {trigger: "ooo", replacement: "\\infty", options: "mA"},
  {trigger: "\\sum", replacement: "\\sum_{${0:i}=${1:1}}^{${2:n}} $3", options: "m"},
  {trigger: "\\prod", replacement: "\\prod_{${0:i}=${1:1}}^{${2:n}} $3", options: "m"},
  {trigger: "limm", replacement: "\\lim_{ ${0:n} \\to ${1:\\infty} } $2", options: "mA"},
  {trigger: "limsup", replacement: "\\limsup_{ ${0:m} \\to ${1:\\infty} } $2", options: "mA"},
  {trigger: "liminf", replacement: "\\liminf_{ ${0:m} \\to ${1:\\infty} } $2", options: "mA"},
  {trigger: "argmin", replacement: "\\mathop{\\mathrm{argmin}}_{$0} $2", options: "mA"},
  {trigger: "argmax", replacement: "\\mathop{\\mathrm{argmax}}_{$0} $2", options: "mA"},
  {trigger: "...", replacement: "\\dots", options: "mA"},
  {trigger: "xx", replacement: "\\times", options: "mA"},
  {trigger: "**", replacement: "\\cdot", options: "mA"},
  {trigger: "_", replacement: "_{$0}$1", options: "mA"},
  {trigger: "^", replacement: "^{$0}$1", options: "mA"},
  {trigger: /([A-Za-z])(\d)/, replacement: "[[0]]_{[[1]]}", options: "rmA", description: "Auto letter subscript", priority: -1},
  {trigger: "invs", replacement: "^{-1}", options: "mA"},
  {trigger: "tp", replacement: "^{\\top}", options: "m"},
  {trigger: "@@", replacement: "^{2}", options: "mA"},
  {trigger: "lr(", replacement: "\\left( $0 \\right) $1", options: "mA"},
	{trigger: "lr{", replacement: "\\left\\{ $0 \\right\\} $1", options: "mA"},
	{trigger: "lr[", replacement: "\\left[ $0 \\right] $1", options: "mA"},
	{trigger: "lr|", replacement: "\\left| $0 \\right| $1", options: "mA"},
	{trigger: "lra", replacement: "\\left< $0 \\right> $1", options: "mA"},
	{trigger: "lrv", replacement: "\\left\\lVert\\vphantom{|} $0 \\right\\rVert $1", options: "mA"},
  {trigger: "lrfloor", replacement: "\\lfloor $0 \\rfloor $1", options: "mA"},
  {trigger: "lrceil", replacement: "\\lceil $0 \\rceil $1", options: "mA"},

  {trigger: ">=", replacement: "\\geq", options: "mA"},
  {trigger: "<=", replacement: "\\leq", options: "mA"},
  {trigger: "=>", replacement: "\\implies", options: "mA"},
  {trigger: "=<", replacement: "\\impliedby", options: "mA"},
  {trigger: "//", replacement: "\\frac{$0}{$1}$2", options: "mA"},

  {trigger: "bcap", replacement: "\\bigcap", options: "mA"},
  {trigger: "bcup", replacement: "\\bigcup", options: "mA"},
  {trigger: "cap", replacement: "\\cap", options: "mA"},
  {trigger: "cup", replacement: "\\cup", options: "mA"},
  {trigger: "inn", replacement: "\\in", options: "mA"},
  {trigger: "notin", replacement: "\\not\\in", options: "mA"},
  {trigger: "\\\\\\", replacement: "\\setminus", options: "mA"},
  {trigger: "eset", replacement: "\\emptyset", options: "mA"},

  {trigger: "CC", replacement: "\\mathbb{C}", options: "mA"},
  {trigger: "RR", replacement: "\\mathbb{R}", options: "mA"},
  {trigger: "QQ", replacement: "\\mathbb{Q}", options: "mA"},
  {trigger: "ZZ", replacement: "\\mathbb{Z}", options: "mA"},
  {trigger: "NN", replacement: "\\mathbb{N}", options: "mA"},
  {trigger: "ev", replacement: "\\mathbb{E}\\left[ $0 \\right]$1", options: "m"},
  {trigger: "evs", replacement: "\\mathbb{E}_{$0}\\left[ $1 \\right]$2", options: "m"},

  // Trigonometry
  {trigger: /([^\\])(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)/, replacement: "[[0]]\\[[1]]", options: "rmA", description: "Add backslash before trig funcs"},

  {trigger: /\\(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)([A-Za-gi-z])/,
    replacement: "\\[[0]] [[1]]", options: "rmA",
    description: "Add space after trig funcs. Skips letter h to allow sinh, cosh, etc."},

  // Environments
  {trigger: "pmat", replacement: "\\begin{pmatrix}\n$0\n\\end{pmatrix}", options: "MA"},
  {trigger: "bmat", replacement: "\\begin{bmatrix}\n$0\n\\end{bmatrix}", options: "MA"},
  {trigger: "Bmat", replacement: "\\begin{Bmatrix}\n$0\n\\end{Bmatrix}", options: "MA"},
  {trigger: "vmat", replacement: "\\begin{vmatrix}\n$0\n\\end{vmatrix}", options: "MA"},
  {trigger: "Vmat", replacement: "\\begin{Vmatrix}\n$0\n\\end{Vmatrix}", options: "MA"},
  {trigger: "matrix", replacement: "\\begin{matrix}\n$0\n\\end{matrix}", options: "MA"},

  {trigger: "pmat", replacement: "\\begin{pmatrix}$0\\end{pmatrix}", options: "nA"},
  {trigger: "bmat", replacement: "\\begin{bmatrix}$0\\end{bmatrix}", options: "nA"},
  {trigger: "Bmat", replacement: "\\begin{Bmatrix}$0\\end{Bmatrix}", options: "nA"},
  {trigger: "vmat", replacement: "\\begin{vmatrix}$0\\end{vmatrix}", options: "nA"},
  {trigger: "Vmat", replacement: "\\begin{Vmatrix}$0\\end{Vmatrix}", options: "nA"},
  {trigger: "matrix", replacement: "\\begin{matrix}$0\\end{matrix}", options: "nA"},

  {trigger: "cases", replacement: "\\begin{cases}\n$0\n\\end{cases}", options: "mA"},
  {trigger: "array", replacement: "\\begin{array}\n$0\n\\end{array}", options: "mA"},
]
